[package]
name = "rocket-n"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
rocket = { version = "0.5.0-rc.2" }
redis = "0.21.5"
rand = "0.8.5"
hex = "0.4.3"
