version: "3.9"

services:
  challenge:
    build: ./chal
    restart: unless-stopped
    ports:
      - "8000:8000"
  selenium:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:8080"